[package]
name = "nativedemo"
version = "0.0.1"
authors = ["Nikita Krupitskas <krupitskaz@gmail.com>"]
edition = "2021"
build = "build.rs"

[dependencies]
libc = "0.2"

[target.'cfg(target_os="android")'.dependencies]
jni = "0.19.0"
image = "0.24.1"
num-complex = "0.4.0"

[lib]
path = "src/lib.rs"
name = "nativedemo"
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
cmake = "0.1.41"
cc = "1.0"
